# Generated by Django 6.1.1 on 2026-09-15 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=80)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='deal',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='prospect',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='stage',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='deal',
            name='contact_source',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='deal',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_deals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deal',
            name='customer_classification',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='deal',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='deal',
            name='expected_close_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='deal',
            name='pipeline',
            field=models.CharField(default='Ventas', max_length=100),
        ),
        migrations.AddField(
            model_name='deal',
            name='source_channel_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='deal',
            name='specialty',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='deal',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='deal',
            name='vertical',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='deal',
            name='visibility',
            field=models.CharField(choices=[('private', 'Privado'), ('shared', 'Compartido')], default='shared', max_length=20),
        ),
        migrations.AddField(
            model_name='prospect',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_prospects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prospect',
            name='customer_classification',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='prospect',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='prospect',
            name='expected_close_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='prospect',
            name='specialty',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='prospect',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='prospect',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='vertical',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='prospect',
            name='visibility',
            field=models.CharField(choices=[('private', 'Privado'), ('shared', 'Compartido')], default='shared', max_length=20),
        ),
        migrations.AlterField(
            model_name='deal',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_deals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_prospects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='deal',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='crm.organization'),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people', to='crm.organization')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('call', 'Llamada'), ('meeting', 'Reunion'), ('email', 'Correo'), ('task', 'Tarea')], default='task', max_length=20)),
                ('due_date', models.DateTimeField()),
                ('duration', models.PositiveIntegerField(default=30)),
                ('status', models.CharField(choices=[('planned', 'Planificada'), ('done', 'Completada'), ('cancelled', 'Cancelada')], default='planned', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.deal')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('prospect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.prospect')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.person')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.AddField(
            model_name='deal',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='crm.person'),
        ),
        migrations.CreateModel(
            name='DealProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_products', to='crm.deal')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.product')),
            ],
        ),
    ]
